apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secrets
  namespace: cloudflare-operator-system # For a default installation, this will be the namespace for cluster resources
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: <API Token>
  CLOUDFLARE_API_KEY: <API Key>
  # CREDENTIAL_FILE is used if found, else CREDENTIAL_SECRET is used to build the file.
  # Either of them is needed when using an existing tunnel
  CLOUDFLARE_TUNNEL_CREDENTIAL_FILE: <~/.cloudflared/tunnelID.json contents>
  CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET: <TunnelSecret from ~/.cloudflared/tunnelID.json>
