apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-recovered
  namespace: namespace1
  labels:
    app: stash-moodle
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
