apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1.platform-as-code
spec:
  insecureSkipTLSVerify: true
  group: platform-as-code
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: default
  version: v1
