apiVersion: v1
kind: ReplicationController
metadata:
  name: kubeplus
  namespace: default
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.18
#      - name: operator-manager
#        image: lmecld/operator-manager:latest
#        imagePullPolicy: IfNotPresent
#        command: [ "/operator-manager"]
#      - name: operator-deployer
#        image: lmecld/operator-deployer:latest
#        imagePullPolicy: IfNotPresent
#        command: [ "/operator-deployer"]
      - name: operator-discovery-helper
        image: lmecld/operator-discovery-helper:0.3.0
        imagePullPolicy: IfNotPresent
        command: [ "/operator-discovery-helper"]
      - name: kube-discovery-apiserver
        image: lmecld/kube-discovery-apiserver:0.3.0
        imagePullPolicy: IfNotPresent
        command: [ "/kube-discovery-apiserver", "--etcd-servers=http://localhost:2379" ]
